"""ExecutionPlan model representing the complete non-executing scheduling plan for a goal workflow."""

import uuid
from datetime import datetime, timezone
from typing import List
from pydantic import BaseModel, Field

from app.scheduler.assignment import TaskAssignment


class ExecutionPlan(BaseModel):
    """Container holding the complete sequence of TaskAssignments generated by the scheduler."""

    plan_id: str = Field(
        default_factory=lambda: str(uuid.uuid4()),
        description="Unique identifier for the generated execution plan.",
    )
    goal_id: str = Field(
        ...,
        description="Goal UUID associated with this execution plan.",
    )
    workflow_id: str = Field(
        ...,
        description="ExecutionDAG workflow UUID associated with this plan.",
    )
    assignments: List[TaskAssignment] = Field(
        default_factory=list,
        description="Ordered list of task assignments mapping DAG nodes to edge devices.",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when the execution plan was generated.",
    )
